config/routes.rb
ToDo::Application.routes.draw do
  

  resources :lists
  resources :tasks

  root to: "lists#index"

end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :name

  has_many :tasks

  validates :name, :presence => true
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :name, :list_id

  belongs_to :lists

  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController


  def index
    @lists = List.all
    @list = List.new
    @task = Task.new 
    @tasks = Task.all
  end

  def create
    @list = List.create( params[:list] )
    if @list.save
      flash[:notice] = "Your list has been added!"
    else
      flash[:notice] = "Enter List field Empty. Could not add List."
    end
    redirect_to :root
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    if @list.update_attributes(params[:list])
      flash[:notice] = "#{@list.name} has been Updated"
      redirect_to :root
    else
      flash[:notice] = "#{@list.name} could not be updated. Try Again"
      redirect_to edit_list_path(@list)
    end
  end

  def destroy 
    @list = List.find(params[:id])
    if @list.destroy
      flash[:notice] = "#{@list.name} has been deleted."
      redirect_to :root
    else
      flash[:notice] = "#{@list.name} could not be deleted."
      redirect_to :root
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController


  def create
    @task = Task.new(params[:task])
    if @task.save
      flash[:notice] = "Your task has been added!"
    else
      flash[:notice] = "Enter Task field Empty. Could not add Task."
    end
    redirect_to :root
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |type, message| %>
  <%= message %>
<% end %>

<%= yield %>

</body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list do |form| %>
  <%= form.label :name, "Enter List" %>
  <%= form.text_field :name %>
  <%= form.submit "Update List" %>
<% end %>

app/views/lists/edit.html.erb
<h1>Edit This List</h1>

<%= render :partial => 'form' %>

app/views/lists/index.html.erb
<h1>ToDo List App</h1>

<% @lists.each do |list| %>
  <h3><%= list.name %> <%= link_to "Edit", edit_list_url(list)%> | <%= link_to "Delete", list_url(list), :method => :delete %></h3>
  <ul>
    <% @tasks.each do |task| %>
    <% if task.list_id == list.id %>
    <li><%= task.name %></li>
    <% end %>
    <% end %>
  </ul>

  <%= form_for [@task] do |f| %>
  <%= f.label :name, "Enter New Task" %>
  <%= f.hidden_field :list_id, :value => list.id %>
  <%= f.text_field :name %>
  <%= f.submit "Submit Task" %>
  <% end %>

<% end %>

<br>
<br>

<%= form_for @list do |form| %>
  <%= form.label :name, "Enter List" %>
  <%= form.text_field :name %>
  <%= form.submit "Submit List" %>
<% end %>

app/views/lists/show.html.erb
<h1>ToDo List App</h1>

<% @lists.each do |list| %>
  <h3><%= list.name %> <%= link_to "Edit", edit_list_url(list)%> | <%= link_to "Delete", list_url(list), :method => :delete %></h3>
  <ul>
    <% @list.tasks.each do |task| %>
    <li><%= task.name %></li>
    <% end %>
  </ul>

    <%= form_for [@list, @task] do |f| %>
    <%= f.label :name, "Enter New Task" %>
    <%= f.text_field :name %>
    <%= f.submit "Submit Task" %>
    <% end %>

<% end %>

<br>
<br>

<%= form_for @list do |form| %>
  <%= form.label :name, "Enter List" %>
  <%= form.text_field :name %>
  <%= form.submit "Submit List" %>
<% end %>

app/views/tasks/new.html.erb
<h2>New Task</h2>